/**
 * HexaBoard.jsx — "Pizarra H.E.X.A. del Día"
 *
 * Landing screen showing automatic MLB insights generated by the backend
 * hexaBoardService. The frontend is a dumb renderer: it does not
 * compute any signal logic.
 */

import { useEffect, useState, useCallback } from 'react';
import { Box, Typography } from '@mui/material';
import { C, BARLOW, MONO } from '../theme';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';

const T = {
  en: {
    title:        'H.E.X.A. DAILY BOARD',
    subtitle:     'Automatic MLB insights for today',
    refresh:      'REFRESH',
    refreshing:   'REFRESHING…',
    loading:      'Computing daily signals…',
    empty:        'No significant signals for today yet.',
    emptyHint:    'Data populates as games finish and lineups are confirmed.',
    error:        'Could not load the board.',
    updated:      'Updated',
    cached:       'cached',
    fresh:        'fresh',
    games:        'games',
    teams:        'teams',
    ago:          (m) => `${m}m ago`,
  },
  es: {
    title:        'PIZARRA H.E.X.A. DEL DÍA',
    subtitle:     'Insights automáticos de MLB para hoy',
    refresh:      'ACTUALIZAR',
    refreshing:   'ACTUALIZANDO…',
    loading:      'Calculando señales del día…',
    empty:        'Aún no hay señales relevantes para hoy.',
    emptyHint:    'Los datos se van llenando conforme terminan los juegos y se confirman los lineups.',
    error:        'No se pudo cargar la pizarra.',
    updated:      'Actualizado',
    cached:       'caché',
    fresh:        'nuevo',
    games:        'juegos',
    teams:        'equipos',
    ago:          (m) => `hace ${m}m`,
  },
};

const TYPE_COLOR = {
  team_streak_hot:       C.accent,
  team_streak_cold:      C.cyan,
  hot_offense:           C.accent,
  cold_offense:          C.cyan,
  bullpen_heavy:         C.amber,
  hit_streak:            C.green,
  cold_batter:           C.cyan,
  high_scoring_matchup:  C.accent,
};

function minutesAgo(iso) {
  if (!iso) return null;
  const ms = Date.now() - new Date(iso).getTime();
  const m = Math.max(0, Math.round(ms / 60000));
  return m;
}

function InsightCard({ insight, lang }) {
  const color = TYPE_COLOR[insight.type] ?? C.cyan;
  const text = insight.text?.[lang] ?? insight.text?.en ?? '';
  return (
    <Box
      sx={{
        display:      'flex',
        alignItems:   'center',
        gap:          '14px',
        px:           '16px',
        py:           '12px',
        bgcolor:      C.surface,
        border:       `1px solid ${C.border}`,
        borderLeft:   `3px solid ${color}`,
        transition:   'all 0.18s',
        '&:hover':    { bgcolor: C.elevated, borderColor: color },
      }}
    >
      <Typography sx={{ fontSize: '1.5rem', lineHeight: 1, userSelect: 'none' }}>
        {insight.icon}
      </Typography>
      <Box sx={{ flex: 1, minWidth: 0 }}>
        <Typography sx={{ fontFamily: MONO, fontSize: '0.92rem', color: C.textPrimary, lineHeight: 1.4 }}>
          {text}
        </Typography>
        <Typography sx={{ fontFamily: MONO, fontSize: '0.6rem', color: C.textMuted, letterSpacing: '0.08em', mt: '2px' }}>
          {insight.type.replace(/_/g, ' ').toUpperCase()}
        </Typography>
      </Box>
    </Box>
  );
}

function SkeletonRow() {
  return (
    <Box sx={{
      height: '54px',
      bgcolor: C.surface,
      border: `1px solid ${C.border}`,
      borderLeft: `3px solid ${C.textGhost}`,
      '@keyframes hxShimmer': {
        '0%, 100%': { opacity: 0.55 },
        '50%':      { opacity: 0.9 },
      },
      animation: 'hxShimmer 1.4s ease-in-out infinite',
    }} />
  );
}

export default function HexaBoard({ lang = 'es' }) {
  const t = T[lang] ?? T.es;
  const [data, setData]       = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError]     = useState(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetchBoard = useCallback(async (force = false) => {
    if (force) setRefreshing(true); else setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_URL}/api/hexa/board${force ? '?force=1' : ''}`);
      const json = await res.json();
      if (!json.success) throw new Error(json.error || 'Unknown error');
      setData(json.data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { fetchBoard(false); }, [fetchBoard]);

  const ageMin = data ? minutesAgo(data.lastUpdatedAt) : null;

  return (
    <Box sx={{ maxWidth: 960, mx: 'auto', width: '100%' }}>
      {/* ── Header ── */}
      <Box sx={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', mb: 2, flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography sx={{
            fontFamily: BARLOW, fontWeight: 800, letterSpacing: '4px',
            fontSize: { xs: '1.2rem', sm: '1.5rem' }, color: C.accent,
            textShadow: '0 0 14px rgba(255,102,0,0.35)',
          }}>
            {t.title}
          </Typography>
          <Typography sx={{ fontFamily: MONO, fontSize: '0.72rem', color: C.textMuted, letterSpacing: '0.1em' }}>
            {t.subtitle}
          </Typography>
        </Box>

        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          {data && (
            <Typography sx={{ fontFamily: MONO, fontSize: '0.65rem', color: C.textMuted, letterSpacing: '0.06em' }}>
              {t.updated}: {ageMin != null ? t.ago(ageMin) : '—'} · {data.cached ? t.cached : t.fresh} · {data.totalGames} {t.games} · {data.teamsAnalyzed} {t.teams}
            </Typography>
          )}
          <Box
            component="button"
            onClick={() => fetchBoard(true)}
            disabled={refreshing || loading}
            sx={{
              px: '14px', py: '6px',
              border: `1px solid ${C.cyanLine}`,
              bgcolor: C.cyanDim,
              color: C.cyan,
              fontFamily: BARLOW,
              fontSize: '0.68rem',
              letterSpacing: '0.14em',
              textTransform: 'uppercase',
              cursor: (refreshing || loading) ? 'default' : 'pointer',
              opacity: (refreshing || loading) ? 0.5 : 1,
              '&:hover': { borderColor: C.cyan, boxShadow: C.cyanGlow, color: '#fff' },
            }}
          >
            {refreshing ? t.refreshing : t.refresh}
          </Box>
        </Box>
      </Box>

      {/* ── Body ── */}
      {loading && !data && (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          {Array.from({ length: 6 }).map((_, i) => <SkeletonRow key={i} />)}
          <Typography sx={{ fontFamily: MONO, fontSize: '0.7rem', color: C.textMuted, textAlign: 'center', mt: 1 }}>
            {t.loading}
          </Typography>
        </Box>
      )}

      {error && !loading && (
        <Box sx={{ p: 3, border: `1px solid ${C.redLine}`, bgcolor: C.redDim, color: C.red, fontFamily: MONO, fontSize: '0.85rem' }}>
          {t.error} — {error}
        </Box>
      )}

      {!loading && !error && data && data.insights.length === 0 && (
        <Box sx={{ p: 3, border: `1px dashed ${C.border}`, textAlign: 'center' }}>
          <Typography sx={{ fontFamily: BARLOW, fontSize: '0.9rem', color: C.textSecondary, letterSpacing: '0.1em' }}>
            {t.empty}
          </Typography>
          <Typography sx={{ fontFamily: MONO, fontSize: '0.7rem', color: C.textMuted, mt: 1 }}>
            {t.emptyHint}
          </Typography>
        </Box>
      )}

      {!loading && !error && data && data.insights.length > 0 && (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          {data.insights.map((insight, i) => (
            <InsightCard key={`${insight.type}-${i}`} insight={insight} lang={lang} />
          ))}
        </Box>
      )}
    </Box>
  );
}
