/** CSS-variable palette — tracks classic + league-kinetic via index.css */
export const PV = {
  bg:          'var(--bg-0)',
  bg0:         'var(--bg-0)',
  bg1:         'var(--bg-1)',
  bg2:         'var(--bg-2)',
  surface:     'var(--bg-1)',
  elevated:    'var(--bg-2)',
  border:      'var(--border)',
  borderLight: 'var(--border-light)',
  cyan:        'var(--neon-cyan)',
  cyanLine:    'var(--neon-cyan-line)',
  cyanDim:     'var(--neon-cyan-dim)',
  green:       'var(--neon-green)',
  greenLine:   'var(--neon-green-line)',
  greenDim:    'var(--neon-green-dim)',
  outcomeWin:       'var(--outcome-win)',
  outcomeWinLine:   'var(--outcome-win-line)',
  outcomeWinDim:    'var(--outcome-win-dim)',
  outcomeLoss:      'var(--outcome-loss)',
  outcomeLossLine:  'var(--outcome-loss-line)',
  outcomeLossDim:   'var(--outcome-loss-dim)',
  outcomePush:      'var(--outcome-push)',
  outcomePushLine:  'var(--outcome-push-line)',
  outcomePushDim:   'var(--outcome-push-dim)',
  red:         'var(--neon-pink)',
  redLine:     'var(--neon-pink-line)',
  redDim:      'var(--neon-pink-dim)',
  amber:       'var(--warning)',
  amberLine:   'var(--warning)',
  amberDim:    'rgba(184, 152, 90, 0.12)',
  accent:      'var(--accent)',
  accentLine:  'var(--neon-orange-line)',
  accentDim:   'var(--neon-orange-dim)',
  ink0:        'var(--ink-0)',
  ink1:        'var(--ink-1)',
  ink2:        'var(--ink-2)',
  textPrimary: 'var(--text-primary)',
  textSecondary: 'var(--ink-1)',
  textMuted:   'var(--text-muted)',
  textDim:     'var(--ink-3)',
  surfaceAlt:  'var(--bg-2)',
  accentGlow:  'var(--neon-orange-glow)',
  line:        'var(--line)',
};
